"""empty message

Revision ID: 35c980f79f4a
Revises: b6937d7592a9
Create Date: 2020-03-21 13:34:52.188815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c980f79f4a'
down_revision = 'b6937d7592a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'seeking_venue')
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'phone')
    op.drop_column('venue', 'image_link')
    op.drop_column('venue', 'facebook_link')
    op.drop_column('venue', 'address')
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'seeking_talent')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'phone')
    op.drop_column('artist', 'image_link')
    op.drop_column('artist', 'genres')
    op.drop_column('artist', 'facebook_link')
    # ### end Alembic commands ###
